/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\neusoft\\exercise\\vue\\quBlog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-77eec519",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77eec519").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-5d39709a",
    path: "/chanllenge/1.Bin2Dec.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d39709a").then(next)
    },
  },
  {
    name: "v-63d09a9e",
    path: "/chanllenge/2.BorderRadiusPreviewer.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-63d09a9e").then(next)
    },
  },
  {
    name: "v-7614e4dd",
    path: "/chanllenge/4.ChristmasLights.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7614e4dd").then(next)
    },
  },
  {
    name: "v-3d4c4d6f",
    path: "/chanllenge/6.ColorCycle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3d4c4d6f").then(next)
    },
  },
  {
    name: "v-2dd8949c",
    path: "/chanllenge/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2dd8949c").then(next)
    },
  },
  {
    path: "/chanllenge/index.html",
    redirect: "/chanllenge/"
  },
  {
    name: "v-1cd289a8",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1cd289a8").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-54b1a656",
    path: "/guide/skos-xl.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-54b1a656").then(next)
    },
  },
  {
    name: "v-5d010c1d",
    path: "/guide/skos%E7%BB%84%E6%88%90.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5d010c1d").then(next)
    },
  },
  {
    path: "/guide/skos组成.html",
    redirect: "/guide/skos%E7%BB%84%E6%88%90.html"
  },
  {
    name: "v-12c07efc",
    path: "/love/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12c07efc").then(next)
    },
  },
  {
    path: "/love/index.html",
    redirect: "/love/"
  },
  {
    name: "v-0f9f3274",
    path: "/vuetest/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f9f3274").then(next)
    },
  },
  {
    path: "/vuetest/index.html",
    redirect: "/vuetest/"
  },
  {
    name: "v-75ac61f5",
    path: "/vuetest/VueTest.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75ac61f5").then(next)
    },
  },
  {
    name: "v-5e23b3fc",
    path: "/wedding/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5e23b3fc").then(next)
    },
  },
  {
    path: "/wedding/index.html",
    redirect: "/wedding/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]