/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "qu's Blog",
  "description": "我的个人网站",
  "base": "/quBlog/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/quBlog/logo.jpg"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/avatar.jpg",
        "actionText": "TODO →",
        "actionLink": "/",
        "features": [
          {
            "title": null,
            "details": "把所有的不快给昨天"
          },
          {
            "title": null,
            "details": "把所有的努力给今天"
          },
          {
            "title": null,
            "details": "把所有的希望给明天"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2020-present qubeijun"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-316652b8",
      "path": "/"
    },
    {
      "title": "4.Christmas Lights",
      "frontmatter": {},
      "regularPath": "/chanllenge/4.ChristmasLights.html",
      "relativePath": "chanllenge/4.ChristmasLights.md",
      "key": "v-61bf9f44",
      "path": "/chanllenge/4.ChristmasLights.html",
      "headers": [
        {
          "level": 2,
          "title": "4.Christmas Lights",
          "slug": "_4-christmas-lights"
        },
        {
          "level": 3,
          "title": "Simulate a string of Christmas lights",
          "slug": "simulate-a-string-of-christmas-lights"
        }
      ]
    },
    {
      "title": "附录B.SKOS标签扩展（SKOS-XL）",
      "frontmatter": {},
      "regularPath": "/guide/skos-xl.html",
      "relativePath": "guide/skos-xl.md",
      "key": "v-8e5a3fd4",
      "path": "/guide/skos-xl.html",
      "headers": [
        {
          "level": 2,
          "title": "附录B.SKOS标签扩展（SKOS-XL）",
          "slug": "附录b-skos标签扩展（skos-xl）"
        },
        {
          "level": 3,
          "title": "B.1. SKOS-XL Namespace and Vocabulary(SKOS-XL命名空间与词汇)",
          "slug": "b-1-skos-xl-namespace-and-vocabulary-skos-xl命名空间与词汇"
        },
        {
          "level": 3,
          "title": "B.2. The skosxl:Label Class",
          "slug": "b-2-the-skosxl-label-class"
        },
        {
          "level": 3,
          "title": "B.2.1. Preamble(序言)",
          "slug": "b-2-1-preamble-序言"
        },
        {
          "level": 3,
          "title": "B.2.2. Class and Property Definitions(类和属性定义)",
          "slug": "b-2-2-class-and-property-definitions-类和属性定义"
        },
        {
          "level": 3,
          "title": "B.2.3. Examples",
          "slug": "b-2-3-examples"
        },
        {
          "level": 3,
          "title": "B.2.4. Notes",
          "slug": "b-2-4-notes"
        },
        {
          "level": 3,
          "title": "B.3. Preferred, Alternate and Hidden skosxl:Labels(首选、备用和隐藏的skosxl:Labels)",
          "slug": "b-3-preferred-alternate-and-hidden-skosxl-labels-首选、备用和隐藏的skosxl-labels"
        },
        {
          "level": 3,
          "title": "B.3.1. Preamble(序言)",
          "slug": "b-3-1-preamble-序言"
        },
        {
          "level": 3,
          "title": "B.3.2. Class and Property Definitions(类和属性定义)",
          "slug": "b-3-2-class-and-property-definitions-类和属性定义"
        },
        {
          "level": 3,
          "title": "B.3.3. Examples",
          "slug": "b-3-3-examples"
        },
        {
          "level": 3,
          "title": "B.3.4. Notes",
          "slug": "b-3-4-notes"
        }
      ]
    },
    {
      "title": "2.Border Radius Previewer",
      "frontmatter": {},
      "regularPath": "/chanllenge/2.BorderRadiusPreviewer.html",
      "relativePath": "chanllenge/2.BorderRadiusPreviewer.md",
      "key": "v-fcde769c",
      "path": "/chanllenge/2.BorderRadiusPreviewer.html",
      "headers": [
        {
          "level": 2,
          "title": "2.Border Radius Previewer",
          "slug": "_2-border-radius-previewer"
        },
        {
          "level": 3,
          "title": "Preview how CSS3 border-radius values affect an element",
          "slug": "preview-how-css3-border-radius-values-affect-an-element"
        }
      ]
    },
    {
      "title": "SKOS组成",
      "frontmatter": {},
      "regularPath": "/guide/skos%E7%BB%84%E6%88%90.html",
      "relativePath": "guide/skos组成.md",
      "key": "v-14ed799e",
      "path": "/guide/skos%E7%BB%84%E6%88%90.html",
      "headers": [
        {
          "level": 2,
          "title": "SKOS组成",
          "slug": "skos组成"
        },
        {
          "level": 2,
          "title": "附录1：SKOS词汇及其与《中分表》对照说明",
          "slug": "附录1：skos词汇及其与《中分表》对照说明"
        },
        {
          "level": 3,
          "title": "1.概念类",
          "slug": "_1-概念类"
        },
        {
          "level": 3,
          "title": "2.概念体系",
          "slug": "_2-概念体系"
        }
      ]
    },
    {
      "title": "1.Bin2Dec",
      "frontmatter": {},
      "regularPath": "/chanllenge/1.Bin2Dec.html",
      "relativePath": "chanllenge/1.Bin2Dec.md",
      "key": "v-ed609598",
      "path": "/chanllenge/1.Bin2Dec.html",
      "headers": [
        {
          "level": 2,
          "title": "1.Bin2Dec",
          "slug": "_1-bin2dec"
        },
        {
          "level": 3,
          "title": "Binary-to-Decimal number converter",
          "slug": "binary-to-decimal-number-converter"
        }
      ]
    },
    {
      "title": "6.ColorCycle",
      "frontmatter": {},
      "regularPath": "/chanllenge/6.ColorCycle.html",
      "relativePath": "chanllenge/6.ColorCycle.md",
      "key": "v-0376d630",
      "path": "/chanllenge/6.ColorCycle.html",
      "headers": [
        {
          "level": 2,
          "title": "6.ColorCycle",
          "slug": "_6-colorcycle"
        },
        {
          "level": 3,
          "title": "Cycle a color value through incremental changes",
          "slug": "cycle-a-color-value-through-incremental-changes"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-7e83d24b",
      "path": "/guide/",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 3,
          "title": "me",
          "slug": "me"
        }
      ]
    },
    {
      "title": "Love",
      "frontmatter": {},
      "regularPath": "/love/",
      "relativePath": "love/README.md",
      "key": "v-13f6d1db",
      "path": "/love/",
      "headers": [
        {
          "level": 2,
          "title": "Love",
          "slug": "love"
        }
      ]
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/chanllenge/",
      "relativePath": "chanllenge/README.md",
      "key": "v-6b72de0a",
      "path": "/chanllenge/",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 3,
          "title": "me",
          "slug": "me"
        }
      ]
    },
    {
      "title": "VueTest",
      "frontmatter": {},
      "regularPath": "/vuetest/VueTest.html",
      "relativePath": "vuetest/VueTest.md",
      "key": "v-ad4ae694",
      "path": "/vuetest/VueTest.html",
      "headers": [
        {
          "level": 2,
          "title": "VueTest",
          "slug": "vuetest"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/wedding/",
      "relativePath": "wedding/README.md",
      "key": "v-1b3bb8ca",
      "path": "/wedding/"
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/vuetest/",
      "relativePath": "vuetest/README.md",
      "key": "v-b844bbda",
      "path": "/vuetest/",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        },
        {
          "level": 3,
          "title": "me",
          "slug": "me"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      },
      {
        "text": "Love",
        "link": "/love/"
      },
      {
        "text": "Wedding",
        "link": "/wedding/"
      },
      {
        "text": "VueTest",
        "link": "/vuetest/"
      },
      {
        "text": "100 DAYS",
        "link": "/chanllenge/"
      },
      {
        "text": "GitHub",
        "link": "https://github.com/qubeijun"
      }
    ],
    "sidebar": {
      "/guide/": [
        "",
        "skos组成",
        "skos-xl"
      ],
      "/love/": [
        ""
      ],
      "/vuetest/": [
        "",
        "VueTest"
      ],
      "/chanllenge/": [
        "",
        "1.Bin2Dec",
        "2.BorderRadiusPreviewer",
        "4.ChristmasLights",
        "6.ColorCycle"
      ]
    }
  }
}